#define MIN(X, Y) (((X) < (Y)) ? (X) : (Y))
#define MAX(X, Y) (((X) > (Y)) ? (X) : (Y))

//###########################################################
// Compute the Givens half-angle, construct the Givens quaternion and the rotation sine/cosine (for the full angle)
//###########################################################

ENABLE_SCALAR_IMPLEMENTATION(Ssh.f=SANPIVOT.f*SANPIVOT.f;)
ENABLE_SCALAR_IMPLEMENTATION(Ssh.ui=(Ssh.f>=Ssmall_number.f)?0xffffffff:0;)
ENABLE_SCALAR_IMPLEMENTATION(Ssh.ui=Ssh.ui&SANPIVOT.ui;)

ENABLE_SCALAR_IMPLEMENTATION(Stmp5.f=0.;)
ENABLE_SCALAR_IMPLEMENTATION(Sch.f=Stmp5.f-SAPIVOT.f;)
ENABLE_SCALAR_IMPLEMENTATION(Sch.f=MAX(Sch.f,SAPIVOT.f);)
ENABLE_SCALAR_IMPLEMENTATION(Sch.f=MAX(Sch.f,Ssmall_number.f);)
ENABLE_SCALAR_IMPLEMENTATION(Stmp5.ui=(SAPIVOT.f>=Stmp5.f)?0xffffffff:0;)

ENABLE_SCALAR_IMPLEMENTATION(Stmp1.f=Sch.f*Sch.f;)
ENABLE_SCALAR_IMPLEMENTATION(Stmp2.f=Ssh.f*Ssh.f;)
ENABLE_SCALAR_IMPLEMENTATION(Stmp2.f=Stmp1.f+Stmp2.f;)
ENABLE_SCALAR_IMPLEMENTATION(Stmp1.f=rsqrt(Stmp2.f);)

ENABLE_SCALAR_IMPLEMENTATION(Stmp4.f=Stmp1.f*Sone_half.f;)
ENABLE_SCALAR_IMPLEMENTATION(Stmp3.f=Stmp1.f*Stmp4.f;)
ENABLE_SCALAR_IMPLEMENTATION(Stmp3.f=Stmp1.f*Stmp3.f;)
ENABLE_SCALAR_IMPLEMENTATION(Stmp3.f=Stmp2.f*Stmp3.f;)
ENABLE_SCALAR_IMPLEMENTATION(Stmp1.f=Stmp1.f+Stmp4.f;)
ENABLE_SCALAR_IMPLEMENTATION(Stmp1.f=Stmp1.f-Stmp3.f;)
ENABLE_SCALAR_IMPLEMENTATION(Stmp1.f=Stmp1.f*Stmp2.f;)

ENABLE_SCALAR_IMPLEMENTATION(Sch.f=Sch.f+Stmp1.f;)

ENABLE_SCALAR_IMPLEMENTATION(Stmp1.ui=~Stmp5.ui&Ssh.ui;)
ENABLE_SCALAR_IMPLEMENTATION(Stmp2.ui=~Stmp5.ui&Sch.ui;)
ENABLE_SCALAR_IMPLEMENTATION(Sch.ui=Stmp5.ui&Sch.ui;)
ENABLE_SCALAR_IMPLEMENTATION(Ssh.ui=Stmp5.ui&Ssh.ui;)
ENABLE_SCALAR_IMPLEMENTATION(Sch.ui=Sch.ui|Stmp1.ui;)
ENABLE_SCALAR_IMPLEMENTATION(Ssh.ui=Ssh.ui|Stmp2.ui;)

ENABLE_SCALAR_IMPLEMENTATION(Stmp1.f=Sch.f*Sch.f;)
ENABLE_SCALAR_IMPLEMENTATION(Stmp2.f=Ssh.f*Ssh.f;)
ENABLE_SCALAR_IMPLEMENTATION(Stmp2.f=Stmp1.f+Stmp2.f;)
ENABLE_SCALAR_IMPLEMENTATION(Stmp1.f=rsqrt(Stmp2.f);)

ENABLE_SCALAR_IMPLEMENTATION(Stmp4.f=Stmp1.f*Sone_half.f;)
ENABLE_SCALAR_IMPLEMENTATION(Stmp3.f=Stmp1.f*Stmp4.f;)
ENABLE_SCALAR_IMPLEMENTATION(Stmp3.f=Stmp1.f*Stmp3.f;)
ENABLE_SCALAR_IMPLEMENTATION(Stmp3.f=Stmp2.f*Stmp3.f;)
ENABLE_SCALAR_IMPLEMENTATION(Stmp1.f=Stmp1.f+Stmp4.f;)
ENABLE_SCALAR_IMPLEMENTATION(Stmp1.f=Stmp1.f-Stmp3.f;)

ENABLE_SCALAR_IMPLEMENTATION(Sch.f=Sch.f*Stmp1.f;)
ENABLE_SCALAR_IMPLEMENTATION(Ssh.f=Ssh.f*Stmp1.f;)

ENABLE_SCALAR_IMPLEMENTATION(Sc.f=Sch.f*Sch.f;)
ENABLE_SCALAR_IMPLEMENTATION(Ss.f=Ssh.f*Ssh.f;)
ENABLE_SCALAR_IMPLEMENTATION(Sc.f=Sc.f-Ss.f;)
ENABLE_SCALAR_IMPLEMENTATION(Ss.f=Ssh.f*Sch.f;)
ENABLE_SCALAR_IMPLEMENTATION(Ss.f=Ss.f+Ss.f;)

//###########################################################
// Rotate matrix A
//###########################################################

ENABLE_SCALAR_IMPLEMENTATION(Stmp1.f=Ss.f*SA11.f;)
ENABLE_SCALAR_IMPLEMENTATION(Stmp2.f=Ss.f*SA21.f;)
ENABLE_SCALAR_IMPLEMENTATION(SA11.f=Sc.f*SA11.f;)
ENABLE_SCALAR_IMPLEMENTATION(SA21.f=Sc.f*SA21.f;)
ENABLE_SCALAR_IMPLEMENTATION(SA11.f=SA11.f+Stmp2.f;)
ENABLE_SCALAR_IMPLEMENTATION(SA21.f=SA21.f-Stmp1.f;)

ENABLE_SCALAR_IMPLEMENTATION(Stmp1.f=Ss.f*SA12.f;)
ENABLE_SCALAR_IMPLEMENTATION(Stmp2.f=Ss.f*SA22.f;)
ENABLE_SCALAR_IMPLEMENTATION(SA12.f=Sc.f*SA12.f;)
ENABLE_SCALAR_IMPLEMENTATION(SA22.f=Sc.f*SA22.f;)
ENABLE_SCALAR_IMPLEMENTATION(SA12.f=SA12.f+Stmp2.f;)
ENABLE_SCALAR_IMPLEMENTATION(SA22.f=SA22.f-Stmp1.f;)

ENABLE_SCALAR_IMPLEMENTATION(Stmp1.f=Ss.f*SA13.f;)
ENABLE_SCALAR_IMPLEMENTATION(Stmp2.f=Ss.f*SA23.f;)
ENABLE_SCALAR_IMPLEMENTATION(SA13.f=Sc.f*SA13.f;)
ENABLE_SCALAR_IMPLEMENTATION(SA23.f=Sc.f*SA23.f;)
ENABLE_SCALAR_IMPLEMENTATION(SA13.f=SA13.f+Stmp2.f;)
ENABLE_SCALAR_IMPLEMENTATION(SA23.f=SA23.f-Stmp1.f;)

//###########################################################
// Update matrix U
//###########################################################

#ifdef COMPUTE_U_AS_MATRIX
ENABLE_SCALAR_IMPLEMENTATION(Stmp1.f=Ss.f*SU11.f;)
ENABLE_SCALAR_IMPLEMENTATION(Stmp2.f=Ss.f*SU12.f;)
ENABLE_SCALAR_IMPLEMENTATION(SU11.f=Sc.f*SU11.f;)
ENABLE_SCALAR_IMPLEMENTATION(SU12.f=Sc.f*SU12.f;)
ENABLE_SCALAR_IMPLEMENTATION(SU11.f=SU11.f+Stmp2.f;)
ENABLE_SCALAR_IMPLEMENTATION(SU12.f=SU12.f-Stmp1.f;)

ENABLE_SCALAR_IMPLEMENTATION(Stmp1.f=Ss.f*SU21.f;)
ENABLE_SCALAR_IMPLEMENTATION(Stmp2.f=Ss.f*SU22.f;)
ENABLE_SCALAR_IMPLEMENTATION(SU21.f=Sc.f*SU21.f;)
ENABLE_SCALAR_IMPLEMENTATION(SU22.f=Sc.f*SU22.f;)
ENABLE_SCALAR_IMPLEMENTATION(SU21.f=SU21.f+Stmp2.f;)
ENABLE_SCALAR_IMPLEMENTATION(SU22.f=SU22.f-Stmp1.f;)

ENABLE_SCALAR_IMPLEMENTATION(Stmp1.f=Ss.f*SU31.f;)
ENABLE_SCALAR_IMPLEMENTATION(Stmp2.f=Ss.f*SU32.f;)
ENABLE_SCALAR_IMPLEMENTATION(SU31.f=Sc.f*SU31.f;)
ENABLE_SCALAR_IMPLEMENTATION(SU32.f=Sc.f*SU32.f;)
ENABLE_SCALAR_IMPLEMENTATION(SU31.f=SU31.f+Stmp2.f;)
ENABLE_SCALAR_IMPLEMENTATION(SU32.f=SU32.f-Stmp1.f;)
#endif
